// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApp.Data;

#nullable disable

namespace QuizApp.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20250806194206_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizApp.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswerIndex")
                        .HasColumnType("int");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswerIndex = 1,
                            Option1 = "Java",
                            Option2 = "C",
                            Option3 = "Python",
                            Option4 = "Assembly",
                            Text = "Which programming language is known as the 'mother of all languages'?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswerIndex = 0,
                            Option1 = "Hyper Text Markup Language",
                            Option2 = "High Tech Modern Language",
                            Option3 = "Home Tool Markup Language",
                            Option4 = "Hyperlink and Text Markup Language",
                            Text = "What does HTML stand for?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswerIndex = 1,
                            Option1 = "Queue",
                            Option2 = "Stack",
                            Option3 = "Array",
                            Option4 = "Linked List",
                            Text = "Which data structure uses LIFO (Last In First Out) principle?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswerIndex = 2,
                            Option1 = "O(n)",
                            Option2 = "O(n²)",
                            Option3 = "O(log n)",
                            Option4 = "O(1)",
                            Text = "What is the time complexity of binary search?"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswerIndex = 2,
                            Option1 = "Microsoft",
                            Option2 = "Apple",
                            Option3 = "Sun Microsystems",
                            Option4 = "IBM",
                            Text = "Which company developed the Java programming language?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswerIndex = 0,
                            Option1 = "Structured Query Language",
                            Option2 = "Simple Query Language",
                            Option3 = "Sequential Query Language",
                            Option4 = "Standard Query Language",
                            Text = "What does SQL stand for?"
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswerIndex = 1,
                            Option1 = "Encapsulation",
                            Option2 = "Compilation",
                            Option3 = "Inheritance",
                            Option4 = "Polymorphism",
                            Text = "Which of the following is NOT an object-oriented programming concept?"
                        },
                        new
                        {
                            Id = 8,
                            CorrectAnswerIndex = 0,
                            Option1 = "2",
                            Option2 = "8",
                            Option3 = "10",
                            Option4 = "16",
                            Text = "What is the base of the binary number system?"
                        },
                        new
                        {
                            Id = 9,
                            CorrectAnswerIndex = 1,
                            Option1 = "Bubble Sort",
                            Option2 = "Quick Sort",
                            Option3 = "Selection Sort",
                            Option4 = "Insertion Sort",
                            Text = "Which sorting algorithm has the best average-case time complexity?"
                        },
                        new
                        {
                            Id = 10,
                            CorrectAnswerIndex = 1,
                            Option1 = "Computer Personal Unit",
                            Option2 = "Central Processing Unit",
                            Option3 = "Control Processing Unit",
                            Option4 = "Central Program Unit",
                            Text = "What does CPU stand for?"
                        },
                        new
                        {
                            Id = 11,
                            CorrectAnswerIndex = 2,
                            Option1 = "MySQL",
                            Option2 = "PostgreSQL",
                            Option3 = "MongoDB",
                            Option4 = "Oracle",
                            Text = "Which of the following is a NoSQL database?"
                        },
                        new
                        {
                            Id = 12,
                            CorrectAnswerIndex = 1,
                            Option1 = "2 bytes",
                            Option2 = "4 bytes",
                            Option3 = "8 bytes",
                            Option4 = "16 bytes",
                            Text = "What is the size of an int data type in C# (on most systems)?"
                        },
                        new
                        {
                            Id = 13,
                            CorrectAnswerIndex = 2,
                            Option1 = "HTTP",
                            Option2 = "SMTP",
                            Option3 = "FTP",
                            Option4 = "POP3",
                            Text = "Which protocol is used to transfer files over the internet?"
                        },
                        new
                        {
                            Id = 14,
                            CorrectAnswerIndex = 0,
                            Option1 = "Application Programming Interface",
                            Option2 = "Advanced Programming Interface",
                            Option3 = "Application Process Integration",
                            Option4 = "Automated Programming Interface",
                            Text = "What does API stand for?"
                        },
                        new
                        {
                            Id = 15,
                            CorrectAnswerIndex = 3,
                            Option1 = "Object-Oriented",
                            Option2 = "Functional",
                            Option3 = "Procedural",
                            Option4 = "Diagonal",
                            Text = "Which of the following is NOT a programming paradigm?"
                        },
                        new
                        {
                            Id = 16,
                            CorrectAnswerIndex = 1,
                            Option1 = "Store data",
                            Option2 = "Speed up queries",
                            Option3 = "Encrypt data",
                            Option4 = "Backup data",
                            Text = "What is the primary purpose of an index in a database?"
                        },
                        new
                        {
                            Id = 17,
                            CorrectAnswerIndex = 1,
                            Option1 = "Queue",
                            Option2 = "Stack",
                            Option3 = "Array",
                            Option4 = "Tree",
                            Text = "Which data structure is used to implement recursion?"
                        },
                        new
                        {
                            Id = 18,
                            CorrectAnswerIndex = 0,
                            Option1 = "Model View Controller",
                            Option2 = "Multi View Container",
                            Option3 = "Main Visual Component",
                            Option4 = "Model Virtual Container",
                            Text = "What does MVC stand for in web development?"
                        },
                        new
                        {
                            Id = 19,
                            CorrectAnswerIndex = 0,
                            Option1 = "Git",
                            Option2 = "Docker",
                            Option3 = "Jenkins",
                            Option4 = "Kubernetes",
                            Text = "Which of the following is a version control system?"
                        },
                        new
                        {
                            Id = 20,
                            CorrectAnswerIndex = 2,
                            Option1 = "8",
                            Option2 = "9",
                            Option3 = "10",
                            Option4 = "11",
                            Text = "What is the decimal equivalent of binary number 1010?"
                        });
                });

            modelBuilder.Entity("QuizApp.Models.QuizScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuizScores");
                });
#pragma warning restore 612, 618
        }
    }
}
